### ISSUE TITLE
Package eplcode.sty inutile ?

### ISSUE THREAD

**Issue by FrancoisDuchene** [UCL-INGI/LINGI1123-Calculabilite#19]
Dans le package de style *lingi1123.sty*, il y a au début du fichier une importation du package *eplcode.sty* alors que le contenu de celui-ci est déjà recopié dans *lingi1123.sty* (ligne 95 à 125) rendant son importation inutile. Ne vaudrait-il donc pas mieux supprimer *eplcode.sty* ? (Bien que cela n'ait pas beaucoup d'impact sur la compilation cela rendrait le code plus lisible)

**Comment by Yves-Deville** [comment]
Oui, mais je n'ai pas réussi.  Si j'enlève l'import de eplcode.sty, cela ne fonctionne pas.  je n'ai pas investiguer comment résoudre cela proprement.  Peut-être que les lignes 95 à 125 ne recouvrent pas exactement ce qu'il y a dans eplcode ?  Si vous avez une idée pour résoudre cela, bienvenu !

**Comment by FrancoisDuchene** [comment]
J'ai supprimé le fichier d'*eplcode.sty* et je me suis permis de nettoyer le code d'*ingi1123.sty* en supprimant les duplications d'importation de packages inutiles et en ordonnant le code. Tout fonctionne.
