### ISSUE TITLE
Ch01: Compléter Détection de virus

### ISSUE THREAD

**Issue by Yves-Deville** [UCL-INGI/LINGI1123-Calculabilite#4]
Compléter la description de la non calculabilité de la détection de virus.
- Définir nuisible
- Préciser ce qu'on veut faire:  démontrer que la fonction detecteur(P,D) ne peut pas être réalisée par un programme qui ne soit pas lui-même nuisible.  
- Expliquer que preuve par contradiction.  Supposons qu'il existe un programme detecteur(P,D) qui ne soit pas nuisible.   Alors il existe un programme pour drole(P).  ...

**Comment by KingOf13** [comment]
\paragraph{Un programme nuisible} est un programme qui, une fois lancé, va aller essayer de recopier son code un peu partout sur le dispositif ayant lancé ledit programme. Un bon anti-virus serait donc un programme qui testerait les programme, voir s'ils s recopient autre part, tout en les empêchant de modifier les autres ficher. Un tel programme, s'il existe, serait du style \texttt{detecteur(P,D)}, avec \texttt{P} le programme à tester, et \texttt{D} un état du système de donnée dans lequel serait exécuté le programme. Or, un tel programme ne peut être non-nuisible. Pour le prouver, imaginons qu'il existe effectivement ce programme \texttt{detecteur(P,D)} non-nuisible, qui renvoie \texttt{true} si le programme est nuisible et \texttt{false} sinon. Dans ce cas, construisons le programme \texttt{drole(P)} qui prend un programme en argument :
\begin{lstlisting}
drole(P)
{
    boolean nuisible = detecteur(P,P);
    if (nuisible) {}
    else copyInDevice(P);
}
\end{lstlisting}
Quand on exécute \texttt{drole(drole)}, \\
\begin{itemize}
\item Soit on considère \texttt{drole(P)} comme non-nuisible, auquel cas \texttt{drole(drole)} va tenter de recopier son code un peu partout, ce qui montre que \texttt{drole(P)} est nuisible;
\item Soit on considère \texttt{drole(P)} comme nuisible, sans que rien ne soit tenté dans le système, et donc le programme \texttt{drole(drole)} ne fait strictement rien, montrant qu'il est non-nuisible.
\end{itemize}
\paragraph{} Nous voyons donc que \texttt{drole(P)} est à la fois détecté comme nuisible et comme non-nuisible, ce qui est impossible, et montre qu'un \texttt{detecteur(P,D)} parfait est impossoble.

**Comment by Yves-Deville** [comment]
Merci d'intégrer vos modification dans le fichier adéquat et de faire un pull request.
