### ISSUE TITLE
Ch04.2.  ND-recursif ssi récursif

### ISSUE THREAD

**Issue by Yves-Deville** [UCL-INGI/LINGI1123-Calculabilite#46]
Démontrer les propriétés "ND-récursif ssi récursif" et "ND-récursivement énumnérable ssi récursivement énumérable".   Bonne idée de d'abord démontrer la propriété précédente sur la simulation d'un programme ND par un programme D.  Faire cette preuve et parler de complexité exponentiel de cette simulation

**Comment by sebcolla** [comment]
Je viens de réaliser une pull request concernant cette issue.
